### PR TITLE
update to react 18.1.0

### PR DESCRIPTION
**Pull request by stevehanstudio**
- **What does this PR do?**

Update React 16.2.0 to 18.1.0. 

Open issues: #295, #328
https://github.com/devfolioco/react-otp-input/issues/295
https://github.com/devfolioco/react-otp-input/issues/328

I tested with the demo app.  Let me know if there's anything else I need to do for this pull request to go through.

- **Any background context you want to provide?**
I tried installing react-opt-input with a React 18.1.0 project but wasn't saw an error message and wasn't able to.

- **Screenshots and/or Live Demo**

### CODE REVIEW

**Comment by IArny** [comment]
@devfolioco could you apply this PR, please

**Review by vishavsolulab — APPROVED** [review]

**Comment by drcoolsanjeev** [comment]
@vishavsolulab 
Looking for this PR to get merged. As its a blocker to upgrade react 18 in a project due to peer dependency issue

**Comment by fatihalp** [comment]
@devfolioco waiting for this merge


> @vishavsolulab Looking for this PR to get merged. As its a blocker to upgrade react 18 in a project due to peer dependency issue

**Review by fatihalp — APPROVED** [review]

**Comment by janschmutz** [comment]
I'm still running into dependency issues for this package with react 17.x and 18.x. Will this be resolved soon?

**Comment by fatihalp** [comment]
use our fork working with react 17



https://www.npmjs.com/package/react-otp-input-visio

> I'm still running into dependency issues for this package with react 17.x and 18.x. Will this be resolved soon?

**Comment by MahdiMhqq** [comment]
See https://github.com/MahdiMhqq/react18-otp-input @janschmutz @IArny @drcoolsanjeev

**Comment by IArny** [comment]
Is project not supported anymore? What's happened? @ajayns @apollonian

**Comment by DjVreditel** [comment]
Merge it please

**Comment by ritikbanger** [comment]
We have a published a new OTP input package right here. Please use this: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
This has been fixed with v3

**Pull request closed without merging**
