### PR TITLE
Changed invalid npm scripts in README

### LINKED ISSUE #162: Incorrect scripts in README.md
Hi there, been using this Component for some time now! Awesome work!

There aren't necessary steps here. I suppose the commands were changed but the README wasn't updated.

Screenshot from 2020-10-02 15-29-53

Screenshot from 2020-10-02 15-30-17

### PR DESCRIPTION
**Pull request by aromalanil**
- **What does this PR do?**
Changes invalid npm scripts in `README` to valid scripts present in `package.json`. Fixes #162

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
Umm, I mean I could have filed a PR myself, right ? I was waiting for a maintainer actually.

**Comment by aromalanil** [comment]
@ShubhankarKG 
Oops! You didn't mention that you could work on this issue. So I thought this was up for grab.

**Comment by ShubhankarKG** [comment]
Ah well, no worries :)

**Comment by apollonian** [comment]
I don't think docz is running correctly at the moment because of the comments in README and since the documentation is still in WIP, it's better to not have the commands until it is all good to go.

**Comment by aromalanil** [comment]
@apollonian So should I remove the docz section from readme?

**Comment by aromalanil** [comment]
@apollonian Okay got it 👍🏻

**Pull request closed without merging**
