### PR TITLE
Add Reat 17 as a valid peer dependency

### PR DESCRIPTION
**Pull request by JPStrydom**
- **What does this PR do?** 
It adds React 17 as a valid peer dependency which should hopefully fix [295](https://github.com/devfolioco/react-otp-input/issues/295)

- **Any background context you want to provide?**
The latest version of this package runs perfectly fine in React 17, it just doesn't list React 17 as one of its peer dependencies so the install step of this package fails when not running it with the `--force` parameter.

### CODE REVIEW

**Review by alexanderdt-ent — APPROVED** [review]
Looks good

**Review by msamaann — APPROVED** [review]

**Review by akaashreedoy — APPROVED** [review]
👌

**Review by shtbik — APPROVED** [review]

**Comment by VTrngNghia** [comment]
Please merge and release :D soon

**Comment by rajatb-git** [comment]
still waiting can we merge this now?

**Comment by barrymichaeldoyle** [comment]
Is this project dead?

**Comment by rajatb-git** [comment]
> Is this project dead?

Yes i think so

**Comment by shubhdwiv12** [comment]
Waiting for this PR to get merged?

**Review by sunnypatel — APPROVED** [review]

**Comment by AsuKaur** [comment]
Hey! Is this released?

**Comment by ritikbanger** [comment]
We have a published a new OTP input package right here. Please use this: https://www.npmjs.com/package/react18-input-otp

**Pull request closed without merging**
