### PR TITLE
Fixed same input not triggering next focus

### LINKED ISSUE #20: Inserting the same number should trigger next input focus
- **Steps to reproduce the issue**:
Write some number on the inputs
Click on an input an type the same value it has

- **Expected**:
The focus jumps to the next input

- **Actual behaviour**:
The focus remains on the same input

**Example**:
```
insert 3 - 4 - 5 - 6
click 3
type 3
```

### PR DESCRIPTION
**Pull request by blenderskool**
- **What does this PR do?**
Fixes #20 

- **Any background context you want to provide?**
When the user entered a number in input with the same number, the next input did not get focused. This PR fixes that.

### CODE REVIEW

**Comment by blenderskool** [comment]
@apollonian I will go through it and fix it 🙂

**Comment by apollonian** [comment]
@blenderskool Awesome, thanks.

**Comment by blenderskool** [comment]
@apollonian On thinking about it, I restructured the event handlers like this:
* `onchange` - When this is triggered, we use it to change the content in OTP
* `oninput` - Use it to move the focus to the next input.

Reasons being that `onchange` is only triggered when the content in the input is changed, and we can't use it to move the focus. Whereas the `oninput` event is triggered when some character input is passed to the input. So irrespective of content in the tag, move the focus to the next input when a character key is pressed.

**Comment by apollonian** [comment]
Will give it a test run!

**Pull request merged**
