### PR TITLE
:pencil2: Update README

### PR DESCRIPTION
**Pull request by apollonian**
Hide placeholder up until next release.

### CODE REVIEW

**Comment by apollonian** [comment]
@allcontributors /help

**Comment by apollonian** [comment]
@all-contributors please add @apollonian for code, design, maintenance, ideas, review
@all-contributors please add @ajayns for code, design, ideas
@all-contributors please add @aromalanil for code

**Comment by apollonian** [comment]
@all-contributors please add @apollonian for code, design, maintenance, ideas, and review

**Comment by apollonian** [comment]
@all-contributors please add @ajayns for code, design, ideas

**Comment by apollonian** [comment]
@all-contributors please add @aromalanil for code

**Comment by apollonian** [comment]
@all-contributors please add @ajayns for code, design, ideas

**Comment by apollonian** [comment]
@all-contributors please add @ajayns for code, design, ideas

**Comment by apollonian** [comment]
Ah, looks like the bot won't recognise that I've already created a config file now.
Sorry about the spam guys. Will add both of you manually.

**Comment by apollonian** [comment]
@all-contributors generate

**Comment by aromalanil** [comment]
Seeing this repo I added this bot to one of my repos yesterday😅.
It was a hell of a struggle for an hour. I think you should merge each PR by this bot individually, as it is creating a new branch for each contributor.

**Comment by apollonian** [comment]
> It was a hell of a struggle for an hour. I think you should merge each PR by this bot individually, as it is creating a new branch for each contributor.

Urgh, I wish I did!

**Pull request merged**
